---
title: 'Figures'
author: "Kevin Wirtz (kevin.wirtz@unistra.fr)"
date: "Updated `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    code_folding: hide
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
    theme: flatly
---

```{r setup, include=FALSE}

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
graphics.off()

Sys.setenv(LANG = "en") # For english language
options(scipen = 5) # To deactivate annoying scientific number notation

library(zoo)
library(tidyverse) # Collection of all the good stuff like dplyr, ggplot2 ect.
library(ggalluvial)
library(cowplot)
library(ggpubr)
library(magick)
library(magrittr)
library(gridExtra)

data_path = file.path("../Data") 
result_path = file.path("../Results/Figures") 

```

# Fig1: Concept evolution

```{r} 
df <- read_csv(file.path(data_path, "Fig1.csv"))
oma2 <- c(0,0,0,0)
df$`minimum income guarantee` = df$`minimum income guarantee`+df$`guaranteed minimum income` + df$`minimum income`
df_long <- df %>%
  select(`basic income`, `minimum income guarantee`, `negative income tax`, `year`) %>%
  filter(year >= 1950 & year <= 2020) %>%
  pivot_longer(cols = -year, 
               names_to = "Variable",  
               values_to = "Value")

# Compute total sum per year
df_long <- df_long %>%
  group_by(year) %>%
  mutate(Total_Sum = sum(Value, na.rm = TRUE),  # Sum of all three variables per year
         Share = Value / Total_Sum * 100) %>%   # Calculate share as percentage
  ungroup()

# Function to calculate 5-year moving average
moving_average <- function(x) {
  rollapply(x, width = 5, FUN = mean, align = "center", fill = NA)
}

# Apply moving average to Share instead of raw Value
df_long <- df_long %>%
  group_by(Variable) %>%
  mutate(MA_Share = moving_average(Share)) %>%
  ungroup()

# View results
print(df_long)
```

```{r} 

custom_colors <- c("First Period" = "orange", "Second Period" = "black", "Third Period" = "#3357FF")

# Create the individual plots
Fig1_a <- ggplot(df_long, aes(x = year, y = MA_Share, color = Variable)) +
  geom_line(linewidth=1) +
  labs(title = "",
       x = "Year",
       y = "Relative Share of Publications",
       color = "Variable") +
  theme(
    axis.text.y = element_text(size = 10),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 10),
    panel.border = element_rect(colour = "black", fill = NA, size = 0.75),
    plot.margin = unit(c(1, 1, 1, 1), "cm"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    legend.position="top",
    strip.text = element_text(size = 8), # Reduce font size of facet labels
    strip.text.x = element_text(margin = margin(b = 5, t = 5))
  )

# Arrange the plots in a 1x3 grid (1 row, 3 columns)
Fig1_a
pdf(file=file.path(result_path, "Fig1.pdf"), width=8, height=6, family="Helvetica", pointsize=6)
#grid.arrange(Fig1_a, Fig1_b, Fig1_c, nrow = 2,ncol=2, layout_matrix=rbind(c(1,1, 2,2), c(NA, 3, 3, NA)))
Fig1_a
dev.off()


```




```{r} 
df <- read_csv(file.path(data_path, "Fig1.csv"))
oma2 <- c(0,0,0,0)
df_long <- df %>%
  pivot_longer(cols = everything()[-1], # exclude year column
               names_to = "Variable",  # name for new column with variable names
               values_to = "Value")

 first_period = c("state bonus", "national dividend", "social dividend", "minimum income", "social credit")
second_period = c("negative income tax", "minimum income guarantee", "minimum income", "guaranteed minimum income", "basic income guarantee", "demogrant", "guaranteed income", "credit income tax", "citizen's wage",
"citizen’s basic income", "citizen’s income", "state bonus", "national dividend", "social dividend", "minimum income", "social credit")
third_period = c("unconditional basic income", "universal basic income", "negative income tax", "minimum income guarantee", "minimum income", "guaranteed minimum income", "basic income guarantee", "demogrant", "guaranteed income", "credit income tax", "citizen's wage",
"citizen’s basic income", "citizen’s income", "state bonus", "national dividend", "social dividend", "minimum income", "social credit") 

# Assign periods
df_long <- df_long %>%
  mutate(Period = case_when(
    Variable %in% first_period ~ "First Period",
    Variable %in% second_period ~ "Second Period",
    Variable %in% third_period ~ "Third Period",
    TRUE ~ "Other"
  ))

# Filter out 'Other' period if needed
df_long <- df_long %>%
  filter(Period != "Other")

df_summary <- df_long %>%
  group_by(Period, year) %>%
  summarise(Total_Value = sum(Value, na.rm = TRUE)) %>%
  ungroup()

# Summarize the data by period and year
df_summary <- df_summary %>%
  filter(year >= 1900 & year <= 2020) %>%
  arrange(year) %>%
  group_by(Period) %>%
  mutate(Smoothed_Total_Value = rollmean(Total_Value, k = 15, fill = NA, align = "center")) %>%
  ungroup() %>%
  group_by(year) %>%
  mutate(Total_Yearly_Value = sum(Smoothed_Total_Value, na.rm = TRUE),
         Share = Smoothed_Total_Value / Total_Yearly_Value * 100) %>%
  ungroup()

```



```{r} 
df_long <- df_long %>%
  group_by(Variable) %>%
  mutate(rollmean_Value = rollmean(Value, k = 10, align = "right", fill = NA))

# Function to create and save plots
create_and_save_plot <- function(df, variable_name) {
  # Filter data for the specific variable
  df_variable <- df %>%
    filter(Variable == variable_name)

  # Create plot
  plot <- ggplot(df_variable, aes(x = year, y = Value)) +
    geom_line(size = 0.75) +
    geom_line(aes(y = rollmean_Value), color = "blue", linetype = "dashed", size = 0.75) +
    labs(title = paste("Publications by Period -", variable_name), x = "Year", y = "N_pubs") +
    theme_minimal()

  # Save plot to PDF
  ggsave(paste0(result_path,paste0(variable_name, "_plot.pdf")), plot, width = 6, height = 4)
}

# Get unique variable names
variable_names <- unique(df_long$Variable)

# Iterate over each variable and create/save plot
for (variable_name in variable_names) {
  create_and_save_plot(df_long, variable_name)
}

```


```{r} 

custom_colors <- c("First Period" = "orange", "Second Period" = "black", "Third Period" = "#3357FF")

# Create the individual plots
Fig1_a <- ggplot(df_summary, aes(x = year, y = Share)) +
  geom_line(linewidth=1,aes(color = Period)) +
  labs(title = "", x = "Year", y = "Share of Publications (%)") +
  scale_color_manual(values = custom_colors) + # Apply custom colors
  theme(
    axis.text.y = element_text(size = 10),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 10),
    panel.border = element_rect(colour = "black", fill = NA, size = 0.75),
    plot.margin = unit(c(1, 1, 1, 1), "cm"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    legend.position="top",
    strip.text = element_text(size = 8), # Reduce font size of facet labels
    strip.text.x = element_text(margin = margin(b = 5, t = 5))
  )

# Arrange the plots in a 1x3 grid (1 row, 3 columns)
Fig1_a
pdf(file=file.path(result_path, "Fig1.pdf"), width=8, height=6, family="Helvetica", pointsize=6)
#grid.arrange(Fig1_a, Fig1_b, Fig1_c, nrow = 2,ncol=2, layout_matrix=rbind(c(1,1, 2,2), c(NA, 3, 3, NA)))
Fig1_a
dev.off()




```