---
title: 'Figures'
author: "Kevin Wirtz (kevin.wirtz@unistra.fr)"
date: "Updated `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    code_folding: hide
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
    theme: flatly
---

```{r setup, include=FALSE}

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
graphics.off()

Sys.setenv(LANG = "en") # For english language
options(scipen = 5) # To deactivate annoying scientific number notation

library(zoo)
library(tidyverse) # Collection of all the good stuff like dplyr, ggplot2 ect.
library(ggalluvial)
library(cowplot)
library(ggpubr)
library(magick)
library(magrittr)
library(gridExtra)

data_path = file.path("../Data") 
result_path = file.path("../Results") 

```

# Fig4: Creativity
```{r} 
df <- read_csv(file.path(data_path, "Fig_creativity.csv"))
mean_df <- df %>%
  group_by(year) %>%
  summarise(across(starts_with("score_"), mean, na.rm = TRUE))

mean_df <- mean_df %>%
  mutate(across(starts_with("score_"), ~ rollmean(.x, 3, fill = NA, align = "right"), .names = "ma_{col}"))


# Reshape for score columns
grouped <- mean_df %>%
  select(year, starts_with("ma_")) %>%
  pivot_longer(-year, names_to = "variable", values_to = "value")

# Calculate 3-point moving average for score columns
grouped <- grouped %>%
  mutate(across(starts_with("score"), ~ rollapply(.x, width = 3, FUN = mean, fill = NA, align = "center")))



```
```{r} 
plot_scores <- ggplot(grouped[grouped$variable=="score_foster",], aes(x = year, y = value, color = variable)) +
  geom_line(size = 1) +
  labs(title = "Mean Scores per Year",
       x = "Year",
       y = "Mean Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 10))

plot_scores
```







# Fig4: Creativity
```{r} 
df <- read_csv(file.path(data_path, "Fig_creativity.csv"))
mean_df <- df %>%
  group_by(year) %>%
  summarise(across(starts_with("score_"):Depth, mean, na.rm = TRUE))


# Reshape for score columns
long_score <- mean_df %>%
  select(year, starts_with("score")) %>%
  pivot_longer(-year, names_to = "variable", values_to = "value")

# Reshape for the remaining columns
long_others <- mean_df %>%
  select(year, DI1:Depth) %>%
  pivot_longer(-year, names_to = "variable", values_to = "value")

```

```{r} 
# Plot for score columns
plot_scores <- ggplot(long_score, aes(x = year, y = value, color = variable)) +
  geom_line(size = 1) +
  labs(title = "Mean Scores per Year",
       x = "Year",
       y = "Mean Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 10))

plot_scores

# Plot for other columns
plot_others <- ggplot(long_others, aes(x = year, y = value, color = variable)) +
  geom_line(size = 1) +
  labs(title = "Mean Values of Other Columns per Year",
       x = "Year",
       y = "Mean Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 10))

plot_others

```




