---
title: 'Figures'
author: "Kevin Wirtz (kevin.wirtz@unistra.fr)"
date: "Updated `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    code_folding: hide
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
    theme: flatly
---

```{r setup, include=FALSE}

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
graphics.off()

Sys.setenv(LANG = "en") # For english language
options(scipen = 5) # To deactivate annoying scientific number notation

library(zoo)
library(tidyverse) # Collection of all the good stuff like dplyr, ggplot2 ect.
library(ggalluvial)
library(cowplot)
library(ggpubr)
library(magick)
library(magrittr)
library(gridExtra)

data_path = file.path("../Data") 
result_path = file.path("../Results/Figures") 

```

# Fig1: Concept evolution

```{r} 
df <- read_csv(file.path(data_path, "Fig_topics2countries_evolution.csv"))
oma2 <- c(0,0,0,0)

df_long <- df %>%
  pivot_longer(
    cols = starts_with("countries_"),
    names_to = "Countries",
    values_to = "value"
  )

df_long <- df_long %>%
  mutate(period = case_when(
    year >= 1960 & year <= 1980 ~ "period1",
    year >= 1981 & year <= 2000 ~ "period2",
    year >= 2001 & year <= 2020 ~ "period3",
    TRUE ~ NA_character_  # To handle any years outside the specified ranges
  ))

df_summarized <- df_long %>%
  group_by(Topics, period, Countries) %>%
  summarize(total_value = sum(value, na.rm = TRUE)) %>%
  ungroup()

# Calculate the share
df_with_share <- df_summarized %>%
  group_by(Countries,period) %>%
  mutate(total_period_value = sum(total_value, na.rm = TRUE),
         share = total_value / total_period_value) %>%
  select(-total_period_value) %>%
  ungroup()%>%
  arrange(Topics, period, Countries)

df_with_share$period <- factor(df_with_share$period, 
                               levels = c("period1", "period2", "period3"), 
                               labels = c("1960-1980", "1981-2000", "2001-2020"))

country_labels <- c("countries_0" = "North Europe",
                    "countries_1" = "USA-Africa-Asia",
                    "countries_2" = "Western Europe",
                    "countries_3" = "America and Pacific")

# Replace country labels in the dataframe
df_with_share$Countries <- factor(df_with_share$Countries, 
                                  levels = names(country_labels), 
                                  labels = country_labels)


```



```{r} 
# Define the custom colors for each community
custom_colors_topics <- c("community_1" = "#ff7e35",
                   "community_2" = "#f381e7",
                   "community_3" = "#00c4ed",
                   "community_4" = "#5cc032",
                   "community_5" = "gray")

# Update the community labels
topic_labels <- c("community_1" = "Social justice",
                      "community_2" = "Tax/Labor supply",
                      "community_3" = "Experiment",
                      "community_4" = "Degrowth",
                      "community_5" = "Others")

Fig1_a = ggplot(df_with_share, aes(x = Countries, y = share, fill = Topics)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~ period, labeller = labeller(period = function(x) {
    return(c("1960-1980", "1981-2000", "2001-2020")[match(x, c("1960-1980", "1981-2000", "2001-2020"))])
  })) +
  labs(title = "",
       x = "Countries",
       y = "Share",
       fill = "Topics") +
  scale_fill_manual(values = custom_colors_topics, labels = topic_labels) + # Apply custom colors and labels
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  )

Fig1_a
pdf(file=file.path(result_path, "Fig_commu_evolution_countries.pdf"), width=8, height=6, family="Helvetica", pointsize=10)
Fig1_a
dev.off()


```

```{r} 
df <- read_csv(file.path(data_path, "Fig_topics2countries_evolution.csv"))
oma2 <- c(0,0,0,0)

df_long <- df %>%
  pivot_longer(
    cols = starts_with("countries_"),
    names_to = "Countries",
    values_to = "value"
  )

df_long <- df_long %>%
  mutate(period = case_when(
    year >= 1960 & year <= 2020 ~ "period1",
    TRUE ~ NA_character_  # To handle any years outside the specified ranges
  ))

df_summarized <- df_long %>%
  group_by(Topics, period, Countries) %>%
  summarize(total_value = sum(value, na.rm = TRUE)) %>%
  ungroup()

# Calculate the share
df_with_share <- df_summarized %>%
  group_by(Countries,period) %>%
  mutate(total_period_value = sum(total_value, na.rm = TRUE),
         share = total_value / total_period_value) %>%
  select(-total_period_value) %>%
  ungroup()%>%
  arrange(Topics, period, Countries)

df_with_share$period <- factor(df_with_share$period, 
                               levels = c("period1"), 
                               labels = c("1960-2020"))

country_labels <- c("countries_0" = "North Europe",
                    "countries_1" = "USA-Africa-Asia",
                    "countries_2" = "Western Europe",
                    "countries_3" = "America and Pacific")

# Replace country labels in the dataframe
df_with_share$Countries <- factor(df_with_share$Countries, 
                                  levels = names(country_labels), 
                                  labels = country_labels)


```

```{r} 
# Define the custom colors for each community
custom_colors_topics <- c("community_1" = "#ff7e35",
                   "community_2" = "#f381e7",
                   "community_3" = "#00c4ed",
                   "community_4" = "#5cc032",
                   "community_5" = "gray")

# Update the community labels
topic_labels <- c("community_1" = "Social justice",
                      "community_2" = "Tax/Labor supply",
                      "community_3" = "Experiment",
                      "community_4" = "Degrowth",
                      "community_5" = "Others")

Fig1_a = ggplot(df_with_share, aes(x = Countries, y = share, fill = Topics)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~ period, labeller = labeller(period = function(x) {
    return(c("1960-1980", "1981-2000", "2001-2020")[match(x, c("1960-1980", "1981-2000", "2001-2020"))])
  })) +
  labs(title = "",
       x = "Countries",
       y = "Share",
       fill = "Topics") +
  scale_fill_manual(values = custom_colors_topics, labels = topic_labels) + # Apply custom colors and labels
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  )

Fig1_a
```

```{r} 
topic_community = 5
df <- read_csv(file.path(data_path, paste0("Fig_topics2countries_evolution_community_", topic_community, ".csv")))
oma2 <- c(0,0,0,0)

df <- df %>%
  mutate(across(`countries_0`:`countries_3`, ~ rollmean(., 5, fill = NA, align = "center")))

df_long <- df %>%
  pivot_longer(
    cols = starts_with("countries_"),
    names_to = "countries",
    values_to = "value"
  )

```

```{r} 

custom_colors <- c("First Period" = "orange", "Second Period" = "black", "Third Period" = "#3357FF")

# Create the individual plots
Fig1_a <- ggplot(df_long, aes(x = year, y = value)) +
  geom_line(linewidth=1,aes(color = countries)) +
  labs(title = paste0("Topic community ", topic_community), x = "Year", y = "Share of Publications (%)") +
  #scale_color_manual(values = custom_colors) + # Apply custom colors
  theme(
    axis.text.y = element_text(size = 10),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 10),
    panel.border = element_rect(colour = "black", fill = NA, size = 0.75),
    plot.margin = unit(c(1, 1, 1, 1), "cm"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.text = element_text(size = 8),
    legend.position="top",
    strip.text = element_text(size = 8), # Reduce font size of facet labels
    strip.text.x = element_text(margin = margin(b = 5, t = 5))
  )

# Arrange the plots in a 1x3 grid (1 row, 3 columns)
Fig1_a
#pdf(file=file.path(result_path, "Fig1.pdf"), width=8, height=6, family="Helvetica", pointsize=6)
#grid.arrange(Fig1_a, Fig1_b, Fig1_c, nrow = 2,ncol=2, layout_matrix=rbind(c(1,1, 2,2), c(NA, 3, 3, NA)))
#Fig1_a
#dev.off()




```