---
title: 'Figures'
author: "Kevin Wirtz (kevin.wirtz@unistra.fr)"
date: "Updated `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    code_folding: hide
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
    theme: flatly
---

```{r setup, include=FALSE}

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
graphics.off()

Sys.setenv(LANG = "en") # For english language
options(scipen = 5) # To deactivate annoying scientific number notation

library(zoo)
library(tidyverse) # Collection of all the good stuff like dplyr, ggplot2 ect.
library(ggalluvial)
library(cowplot)
library(ggpubr)
library(magick)
library(magrittr)
library(gridExtra)

data_path = file.path("../Data") 
result_path = file.path("../Results/Figures") 

```

# Fig1: Concept evolution

```{r} 
df <- read_csv(file.path(data_path, "Fig_countries2keywords_v2.csv"))
oma2 <- c(0,0,0,0)

df_long <- df %>%
  pivot_longer(
    cols = starts_with("countries_"),
    names_to = "Countries",
    values_to = "value"
  )

df_long <- df_long %>%
  mutate(period = case_when(
    year >= 1960 & year <= 1980 ~ "period1",
    year >= 1981 & year <= 2000 ~ "period2",
    year >= 2001 & year <= 2020 ~ "period3",
    TRUE ~ NA_character_  # To handle any years outside the specified ranges
  ))

df_summarized <- df_long %>%
  group_by(definition, period, Countries) %>%
  summarize(total_value = sum(value, na.rm = TRUE)) %>%
  ungroup()

# Calculate the share
df_with_share <- df_summarized %>%
  group_by(Countries,period) %>%
  mutate(total_period_value = sum(total_value, na.rm = TRUE),
         share = total_value / total_period_value) %>%
  select(-total_period_value) %>%
  ungroup()%>%
  arrange(definition, period, Countries)

df_with_share$period <- factor(df_with_share$period, 
                               levels = c("period1", "period2", "period3"), 
                               labels = c("1960-1980", "1981-2000", "2001-2020"))

country_labels <- c("countries_0" = "North Europe",
                    "countries_1" = "USA-Africa-Asia",
                    "countries_2" = "Western Europe",
                    "countries_3" = "America and Pacific")

# Replace country labels in the dataframe
df_with_share$Countries <- factor(df_with_share$Countries, 
                                  levels = names(country_labels), 
                                  labels = country_labels)


```



```{r} 
# Define the custom colors for each community
custom_colors_topics <- c("community_1" = "#ff7e35",
                   "community_2" = "#f381e7",
                   "community_3" = "#00c4ed",
                   "community_4" = "#5cc032",
                   "community_5" = "gray")

# Update the community labels
topic_labels <- c("community_1" = "Social justice",
                      "community_2" = "Tax/Labor supply",
                      "community_3" = "Experiment",
                      "community_4" = "Degrowth",
                      "community_5" = "Others")

Fig1_a = ggplot(df_with_share, aes(x = Countries, y = share, fill = definition)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~ period, labeller = labeller(period = function(x) {
    return(c("1960-1980", "1981-2000", "2001-2020")[match(x, c("1960-1980", "1981-2000", "2001-2020"))])
  })) +
  labs(title = "",
       x = "Countries",
       y = "Share",
       fill = "Definition") +
  #(values = custom_colors_topics, labels = topic_labels) + # Apply custom colors and labels
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  )

Fig1_a



```

```{r} 
df <- read_csv(file.path(data_path, "Fig_topics2keywords_v2.csv"))
oma2 <- c(0,0,0,0)

df_long <- df %>%
  pivot_longer(
    cols = starts_with("communities_"),
    names_to = "Community",
    values_to = "value"
  )

df_long <- df_long %>%
  mutate(period = case_when(
    year >= 1960 & year <= 1980 ~ "period1",
    year >= 1981 & year <= 2000 ~ "period2",
    year >= 2001 & year <= 2020 ~ "period3",
    TRUE ~ NA_character_  # To handle any years outside the specified ranges
  ))

df_summarized <- df_long %>%
  group_by(definition, period, Community) %>%
  summarize(total_value = sum(value, na.rm = TRUE)) %>%
  ungroup()

# Calculate the share
df_with_share <- df_summarized %>%
  group_by(Community,period) %>%
  mutate(total_period_value = sum(total_value, na.rm = TRUE),
         share = total_value / total_period_value) %>%
  select(-total_period_value) %>%
  ungroup()%>%
  arrange(definition, period, Community)

df_with_share$period <- factor(df_with_share$period, 
                               levels = c("period1", "period2", "period3"), 
                               labels = c("1960-1980", "1981-2000", "2001-2020"))

community_labels <- c("communities_1" = "Social justice",
                    "communities_2" = "Tax/Labor supply",
                    "communities_3" = "Experiment",
                    "communities_4" = "Degrowth",
                    "communities_5" = "Others")

# Replace country labels in the dataframe
df_with_share$Countries <- factor(df_with_share$Community, 
                                  levels = names(community_labels), 
                                  labels = community_labels)


```

```{r} 
# Define the custom colors for each community
custom_colors_topics <- c("community_1" = "#ff7e35",
                   "community_2" = "#f381e7",
                   "community_3" = "#00c4ed",
                   "community_4" = "#5cc032",
                   "community_5" = "gray")

# Update the community labels
topic_labels <- c("community_1" = "Social justice",
                      "community_2" = "Tax/Labor supply",
                      "community_3" = "Experiment",
                      "community_4" = "Degrowth",
                      "community_5" = "Others")

Fig1_b = ggplot(df_with_share, aes(x = Countries, y = share, fill = definition)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~ period, labeller = labeller(period = function(x) {
    return(c("1960-1980", "1981-2000", "2001-2020")[match(x, c("1960-1980", "1981-2000", "2001-2020"))])
  })) +
  labs(title = "",
       x = "Countries",
       y = "Share",
       fill = "Definition") +
  #(values = custom_colors_topics, labels = topic_labels) + # Apply custom colors and labels
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  )

Fig1_b



```

```{r} 
df <- read_csv(file.path(data_path, "Fig_topics2definitions_v2.csv"))
oma2 <- c(0,0,0,0)

df_long <- df %>%
  pivot_longer(
    cols = starts_with("communities_"),
    names_to = "Community",
    values_to = "value"
  )

df_long <- df_long %>%
  mutate(period = case_when(
    year >= 1960 & year <= 1980 ~ "period1",
    year >= 1981 & year <= 2000 ~ "period2",
    year >= 2001 & year <= 2020 ~ "period3",
    TRUE ~ NA_character_  # To handle any years outside the specified ranges
  ))

df_summarized <- df_long %>%
  group_by(definition, period, Community) %>%
  summarize(total_value = sum(value, na.rm = TRUE)) %>%
  ungroup()

# Calculate the share
df_with_share <- df_summarized %>%
  group_by(Community,period) %>%
  mutate(total_period_value = sum(total_value, na.rm = TRUE),
         share = total_value / total_period_value) %>%
  select(-total_period_value) %>%
  ungroup()%>%
  arrange(definition, period, Community)

df_with_share$period <- factor(df_with_share$period, 
                               levels = c("period1", "period2", "period3"), 
                               labels = c("1960-1980", "1981-2000", "2001-2020"))

community_labels <- c("communities_1" = "Social justice",
                    "communities_2" = "Tax/Labor supply",
                    "communities_3" = "Experiment",
                    "communities_4" = "Degrowth",
                    "communities_5" = "Others")

# Replace country labels in the dataframe
df_with_share$Countries <- factor(df_with_share$Community, 
                                  levels = names(community_labels), 
                                  labels = community_labels)



```

```{r} 
# Define the custom colors for each community
custom_colors_topics <- c("community_1" = "#ff7e35",
                   "community_2" = "#f381e7",
                   "community_3" = "#00c4ed",
                   "community_4" = "#5cc032",
                   "community_5" = "gray")

# Update the community labels
topic_labels <- c("community_1" = "Social justice",
                      "community_2" = "Tax/Labor supply",
                      "community_3" = "Experiment",
                      "community_4" = "Degrowth",
                      "community_5" = "Others")

Fig1_a = ggplot(df_with_share, aes(x = Countries, y = share, fill = definition)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_wrap(~ period, labeller = labeller(period = function(x) {
    return(c("1960-1980", "1981-2000", "2001-2020")[match(x, c("1960-1980", "1981-2000", "2001-2020"))])
  })) +
  labs(title = "",
       x = "Countries",
       y = "Share",
       fill = "Definition") +
  #(values = custom_colors_topics, labels = topic_labels) + # Apply custom colors and labels
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "right",
    legend.text = element_text(size = 8)
  )

Fig1_a



```