---
title: 'Figures'
author: "Kevin Wirtz (kevin.wirtz@unistra.fr)"
date: "Updated `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    code_folding: hide
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
    theme: flatly
---

```{r setup, include=FALSE}

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
gc() #free up memrory and report the memory usage.
graphics.off()

Sys.setenv(LANG = "en") # For english language
options(scipen = 5) # To deactivate annoying scientific number notation

library(zoo)
library(tidyverse) # Collection of all the good stuff like dplyr, ggplot2 ect.
library(ggalluvial)
library(cowplot)
library(ggpubr)
library(magick)
library(magrittr)
library(gridExtra)

data_path = file.path("../Data") 
result_path = file.path("../Results") 

```

# Fig intro

```{r} 
df <- read_csv(file.path(data_path, "Fig_intro.csv"))
oma2 <- c(0,0,0,0)
df$share = df$Value2/df$Value1
df$share_ma <- rollmean(df$share, k = 5, fill = NA, align = "center")

```

```{r} 
oma2 <- c(0.3,0,0,0.3)

colors <- c("UBI publications" = "#1f77b4", "share SHS" = "#ff7f0e")


fig_intro = ggplot(df[df$year<=2020,], aes(x = year)) + 
  geom_line(linewidth=1,aes(y = Value2, color='UBI_publications')) + 
  geom_line(linewidth=1,aes(y = share_ma*6768480, color='UBI_share')) +
  scale_color_manual(name = "Group",
                     values = c( "UBI_publications" = "#1f77b4", "UBI_share" = "black"),
                     labels = c( "UBI publications","Share UBI publications in SHS")) +
  labs(x = "Year",
         y = "Share",
         color = "Legend",
       title="Evolution of UBI related publications") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 6),
      axis.text.y = element_text(size = 6),
      axis.title.x = element_text(size = 6),
      axis.title.y = element_text(size = 6),
      panel.border = element_rect(colour = "black", fill=NA, size=0.75),
      plot.margin = unit(oma2, "cm"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      plot.title = element_text(hjust = 0.5, size = 12),  
      legend.key=element_blank(),
      legend.title=element_blank(),
      legend.position="top",
      legend.text=element_text(size = 6)) +
  scale_y_continuous(
    name = "Publications",
    sec.axis = sec_axis(~./6768480, name="Share")
  )
fig_intro
pdf(file=file.path(result_path, "Figures/Fig_intro.pdf"), width=8, height=5, family="Helvetica", pointsize=6)
fig_intro
dev.off()
```


# Fig1: Concept evolution

```{r} 
df <- read_csv(file.path(data_path, "Fig1.csv"))
oma2 <- c(0,0,0,0)
df_long <- df %>%
  pivot_longer(cols = everything()[-1], # exclude year column
               names_to = "Variable",  # name for new column with variable names
               values_to = "Value")

first_period = c("state bonus", "minimum income", "national dividend", "social dividend", "basic minimum income", "basic income")
second_period = c("negative income tax", "minimum income guarantee","minimum income", "guaranteed minimum income", "basic income guarantee", "demogrant", "guaranteed income", "credit income tax",
"citizen’s basic income", "citizen’s income")
third_period = c("helicopter money", "quantitative easing","unconditional basic income", "universal basic income","basic income")

df_period1 <- df_long[df_long$Variable %in% first_period & df_long$year>1910 & df_long$year<1941 , ]
df_period2 <- df_long[df_long$Variable %in% second_period & df_long$year>1960 & df_long$year<1971 , ]
df_period3 <- df_long[df_long$Variable %in% third_period & df_long$year>2010 & df_long$year<2025 , ]

```

```{r} 
# Create the individual plots
Fig1_a <- ggplot(df_period1, aes(x = year, y = Value)) +
  geom_line(aes(color = Variable), size = 0.75) +
  labs(title = "Period 1", x = "year", y = "# Publications") +
    theme(
        axis.text.y = element_text(size = 10),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        plot.margin = unit(oma2, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 6),
        strip.text = element_text(size = 8), # Reduce font size of facet labels
        strip.text.x = element_text(margin = margin(b = 5, t = 5))) 


Fig1_b <- ggplot(df_period2, aes(x = year, y = Value)) +
  geom_line(aes(color = Variable), size = 0.75) +
  labs(title = "Period 2", x = "year", y = "# Publications") +
    theme( # Remove x-axis ticks
        axis.text.y = element_text(size = 10),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        plot.margin = unit(oma2, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 6),
        strip.text = element_text(size = 8), # Reduce font size of facet labels
        strip.text.x = element_text(margin = margin(b = 5, t = 5))) 


Fig1_c <- ggplot(df_period3, aes(x = year, y = Value)) +
  geom_line(aes(color = Variable), size = 0.75) +
  labs(title = "Period 3", x = "year", y = "# Publications") +
    theme(
        axis.text.y = element_text(size = 10),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        plot.margin = unit(oma2, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        # Legend position with justification for top left corner
        legend.justification = "left",  # Added justification
        legend.text = element_text(size = 6),
        strip.text = element_text(size = 8), # Reduce font size of facet labels
        strip.text.x = element_text(margin = margin(b = 5, t = 5))) 


# Arrange the plots in a 1x3 grid (1 row, 3 columns)

pdf(file=file.path(result_path, "Figures/Fig1.pdf"), width=8, height=6, family="Helvetica", pointsize=6)
grid.arrange(Fig1_a, Fig1_b, Fig1_c, nrow = 2,ncol=2, layout_matrix=rbind(c(1,1, 2,2), c(NA, 3, 3, NA)))
dev.off()

```

# Fig2: Theo vs Expe
```{r} 
df <- read_csv(file.path(data_path, "Fig2.csv"))
df$Journal <- sapply(str_split(df$Journal, "/"), function(x) x[length(x)])
df$Journal <- str_wrap(df$Journal, width = 30)
df_long <- df %>%
  pivot_longer(cols = c(n_theo, n_expe), names_to = "Type", values_to = "Count")
```
```{r} 
Fig2 <- ggplot(df_long, aes(x = Type, y = Count, fill = Type)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~Journal, ncol = 4) +
  scale_fill_manual(name = "Type",
                    values = c("n_theo" = "#1f77b4", "n_expe" = "#fb7d07"),
                    labels = c("Experimental", "Theoretical")) +
  labs(x = "",
       y = "Number of Publications",
       fill = "Legend") +
    theme(axis.text.x = element_blank(),  # Remove x-axis text
        axis.ticks.x = element_blank(), # Remove x-axis ticks
        axis.text.y = element_text(size = 10),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        plot.margin = unit(oma2, "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 10),
        strip.text = element_text(size = 8), # Reduce font size of facet labels
        strip.text.x = element_text(margin = margin(b = 5, t = 5))) 


Fig2

pdf(file=file.path(result_path, "Figures/Fig2.pdf"), width=8, height=8, family="Helvetica", pointsize=6)
Fig2
dev.off()

```

```{r} 

figa = ggplot(collapsed_df, aes(x = year)) + 
  geom_line(size=1,aes(y = share_transition_roll, color='share_ai_transition')) + 
  geom_line(size=1,aes(y = share_transition_non_ai_roll, color='share_non_ai_transition')) +
  scale_color_manual(name = "Group",
                     values = c( "share_ai_transition" = "#1f77b4", "share_non_ai_transition" = "black"),
                     labels = c( "AI researchers","Non-AI researchers")) +
  labs(x = "Year",
         y = "Share of researchers leaving academia",
         color = "Legend") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
      axis.text.y = element_text(size = 10),
      axis.title.x = element_text(size = 10),
      axis.title.y = element_text(size = 10),
      panel.border = element_rect(colour = "black", fill=NA, size=0.75),
      plot.margin = unit(oma2, "cm"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      legend.key=element_blank(),
      legend.title=element_blank(),
      legend.position="top",
      legend.text=element_text(size = 10)) #+
#  scale_y_continuous(
#    name = "Share transition",
#    sec.axis = sec_axis(~./3, name="Share Ind.")
#  )

figa


pdf(file=file.path(result_path, "plots/Fig_intro_a.pdf"), width=8, height=5, family="Helvetica", pointsize=6)
figa
dev.off()

```

```{r} 

figb = ggplot(collapsed_df, aes(x = year)) + 
  geom_line(size=1,aes(y = share_company_roll, color='share_ai_transition')) + 
  geom_line(size=1,aes(y = share_company_non_ai_roll, color='share_non_ai_transition')) +
  scale_color_manual(name = "Group",
                     values = c( "share_ai_transition" = "#1f77b4", "share_non_ai_transition" = "black"),
                     labels = c( "AI researchers","Non-AI researchers")) +
  labs(x = "Year",
         y = "Share of researchers leaving academia to industry",
         color = "Legend") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
      axis.text.y = element_text(size = 10),
      axis.title.x = element_text(size = 10),
      axis.title.y = element_text(size = 10),
      panel.border = element_rect(colour = "black", fill=NA, size=0.75),
      plot.margin = unit(oma2, "cm"),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      legend.key=element_blank(),
      legend.title=element_blank(),
      legend.position="top",
      legend.text=element_text(size = 10)) #+
#  scale_y_continuous(
#    name = "Share solo aut",
#    sec.axis = sec_axis(~./3, name="Share Ind.")
#  )

figb


pdf(file=file.path(result_path, "plots/Fig_intro_b.pdf"), width=8, height=5, family="Helvetica", pointsize=6)
figb
dev.off()

```

# Fig4: Creativity
```{r} 
df <- read_csv(file.path(data_path, "Fig_creativity.csv"))
mean_df <- df %>%
  group_by(year) %>%
  summarise(across(starts_with("score_"):Depth, mean, na.rm = TRUE))


# Reshape for score columns
long_score <- mean_df %>%
  select(year, starts_with("score")) %>%
  pivot_longer(-year, names_to = "variable", values_to = "value")

# Reshape for the remaining columns
long_others <- mean_df %>%
  select(year, DI1:Depth) %>%
  pivot_longer(-year, names_to = "variable", values_to = "value")

```

```{r} 
# Plot for score columns
plot_scores <- ggplot(long_score, aes(x = year, y = value, color = variable)) +
  geom_line(size = 1) +
  labs(title = "Mean Scores per Year",
       x = "Year",
       y = "Mean Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 10))

plot_scores

# Plot for other columns
plot_others <- ggplot(long_others, aes(x = year, y = value, color = variable)) +
  geom_line(size = 1) +
  labs(title = "Mean Values of Other Columns per Year",
       x = "Year",
       y = "Mean Value") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        panel.border = element_rect(colour = "black", fill=NA, size=0.75),
        plot.margin = unit(c(1, 1, 1, 1), "cm"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 10))

plot_others

```



